swipe:
  4:
    # 窗口:切换最大化状态
    up:
      sendkey: "leftalt+f10"
    # 窗口: 隐藏窗口
    down:
      sendkey: "leftctrl+leftshift+leftalt+v"
    # 导航: 移动到右侧工作区
    left:
      sendkey: "leftctrl+leftshift+leftalt+l"
    # 导航: 移动到左侧工作区
    right:
      sendkey: "leftctrl+leftshift+leftalt+h"
hold:
  3:
   begin:
     # 窗口: 移动窗口
     sendkey: "leftalt+M"
  4:
    begin:
      # 窗口: 关闭窗口
      sendkey: "leftalt+f4" 
pinch:
  2:
    in:
      begin:
        #sendkey: "leftalt+f10"
        command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom in
    out:
      begin:
        #sendkey: "leftalt+f10"
        command: 'xdotool keydown ctrl click 4 keyup ctrl' # Zoom out
---
context:
  application: Google-chrome
swipe:
  3:
    left:
      sendkey: "leftctrl+tab"
    right:
      sendkey: "leftctrl+leftshift+tab"
    up:
      command: 'xdotool key alt+Left'
    down:
      command: 'xdotool key alt+Right'
---
context:
  application: eDEX-UI
swipe:
  3:
    left:
      command: 'xdotool key ctrl+Tab'
    right:
      command: 'xdotool key ctrl+shift+Tab'
---
context:
  application: Gnome-terminal
swipe:
  3:
    left:
      command: 'xdotool key ctrl+Page_Down'
    right:
      command: 'xdotool key ctrl+Page_Up'
---
context:
  application: Org.gnome.Nautilus
swipe:
  3:
    left:
      command: 'xdotool key ctrl+Page_Down'
    right:
      command: 'xdotool key ctrl+Page_Up'
    up:
      command: 'xdotool key alt+Left'
    down:
      command: 'xdotool key alt+Right'
---
context:
  application: Code
swipe:
  3:
    left:
      command: 'xdotool key ctrl+Page_Down'
    right:
      command: 'xdotool key ctrl+Page_Up'
    up:
      command: 'xdotool key ctrl+alt+minus' # ctrl+alt+-
    down:
      command: 'xdotool key ctrl+alt+shift+minus' # ctrl+alt+=
